import type { RecommendedProduct } from "@/lib/types";

/** Catalogue complet du matériel Irrigate (checklist utilisateur). */
export const EQUIPMENT_CATALOG: RecommendedProduct[] = [
  {
    id: "kit-goutte-enterre-idf",
    name: "Kit goutte-à-goutte enterré 25 m",
    category: "irrigation",
    description: "Tuyau poreux + raccords + vanne",
    priceEstimate: 45,
    reason: "Réseau enterré",
    shopHint: "Jardinerie / brico",
  },
  {
    id: "kit-goutte-surface",
    name: "Kit goutte-à-goutte surface 20 m",
    category: "irrigation",
    description: "Goutteurs autorégulants + programmateur",
    priceEstimate: 32,
    reason: "Installation rapide",
    shopHint: "Leroy Merlin, Jardiland…",
  },
  {
    id: "aspersion-auto",
    name: "Kit aspersion programmé 3 arroseurs",
    category: "irrigation",
    description: "Électrovanne + programmateur",
    priceEstimate: 89,
    reason: "Grandes parcelles",
    shopHint: "Spécialiste arrosage",
  },
  {
    id: "tuyau-renforce",
    name: "Tuyau d'arrosage renforcé 25 m + lance",
    category: "irrigation",
    description: "Arrosage manuel par zones",
    priceEstimate: 35,
    reason: "Mode jet d'eau",
    shopHint: "Bricolage",
  },
  {
    id: "arrosoir-6l",
    name: "Arrosoir gradué 6 L",
    category: "outil",
    description: "Précision au pied des plants",
    priceEstimate: 18,
    reason: "Arrosage manuel",
    shopHint: "Bricolage / jardin",
  },
  {
    id: "programmateur",
    name: "Programmateur d'arrosage",
    category: "irrigation",
    description: "Minuterie mécanique ou numérique",
    priceEstimate: 25,
    reason: "Automatisation",
    shopHint: "Jardinerie",
  },
  {
    id: "electrovanne",
    name: "Électrovanne 24 V",
    category: "irrigation",
    description: "Pilotage du réseau",
    priceEstimate: 30,
    reason: "Aspersion / goutte-à-goutte auto",
    shopHint: "Spécialiste arrosage",
  },
  {
    id: "regulateur-pression",
    name: "Régulateur de pression 2 bar",
    category: "irrigation",
    description: "Stabilise la pression en amont",
    priceEstimate: 15,
    reason: "Grandes parcelles",
    shopHint: "Jardinerie pro",
  },
  {
    id: "serre-tunnel",
    name: "Serre tunnel 3 × 4 m",
    category: "outil",
    description: "Structure + bâche",
    priceEstimate: 189,
    reason: "Variétés sensibles au froid",
    shopHint: "Jardinerie",
  },
  {
    id: "compost-local",
    name: "Compost mûr 40 L",
    category: "engrais",
    description: "Amendement organique",
    priceEstimate: 8,
    reason: "Fertilisation",
    shopHint: "Jardinerie",
  },
  {
    id: "bêche",
    name: "Bêche ou grelinette",
    category: "outil",
    description: "Travail du sol",
    priceEstimate: 35,
    reason: "Préparation parcelle",
    shopHint: "Bricolage",
  },
  {
    id: "paillage",
    name: "Paillage paille / BRF",
    category: "outil",
    description: "Limitation évaporation",
    priceEstimate: 12,
    reason: "Économie d'eau",
    shopHint: "Jardinerie",
  },
];
